# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'test17' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for test17

  target 'test17-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'test17Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'test17-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for test17-tvOS

  target 'test17-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
